general:
  kafka-topic: transactions-topic

spring:
  kafka:
    producer:
#      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: midas-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
#    bootstrap-servers: "${spring.embedded.kafka.brokers}"
    listener:
      concurrency: 1
    logging:
      level:
        org.apache.kafka.clients.producer: DEBUG




